set(CMAKE_DEBUG_POSTFIX -debug)
set_target_properties(${LIBRARY_NAME}
    PROPERTIES
    VERSION "${LIBRARY_VERSION}"
    SOVERSION "${LIBRARY_VERSION_MAJOR}"
    DEBUG_POSTFIX ${CMAKE_DEBUG_POSTFIX}
)
